[build]
command = "npm run start"  # Specify the build command if needed
functions = "C:\\personnel\\ekart-back\\functions"    # Specify the folder containing serverless functions

[dev]
targetPort = 3333
functions = "C:\\personnel\\ekart-back\\functions"
